DIRECTION_UP = "up"
DIRECTION_DOWN = "down"
DIRECTION_NORTH = "north"
DIRECTION_SOUTH = "south"
DIRECTION_EAST = "east"
DIRECTION_WEST = "west"
DIRECTION_NORTHWEST = "northwest"
DIRECTION_NORTHEAST = "northeast"
DIRECTION_SOUTHWEST = "southwest"
DIRECTION_SOUTHEAST = "southeast"
DIRECTION_SWIMMING = "swim"
DIRECTION_FLYING = "fly"
DIRECTION_CLIMBING = "climb"

DIRECTIONS_DB = [
    DIRECTION_UP,
    DIRECTION_DOWN,
    DIRECTION_NORTH,
    DIRECTION_SOUTH,
    DIRECTION_EAST,
    DIRECTION_WEST,
    DIRECTION_NORTHWEST,
    DIRECTION_NORTHEAST,
    DIRECTION_SOUTHWEST,
    DIRECTION_SOUTHEAST,
    DIRECTION_SWIMMING,
    DIRECTION_FLYING,
    DIRECTION_CLIMBING,
]
